version: '3.8' # /home/ubuntu/Development/Projects/hl-ubuntu-01/docker-compose.yml
services:
    # Homer
    homerserver:
      container_name: docker_homer
      image: b4bz/homer
#      build: 
#        context: .
#        dockerfile: Dockerfile.homer
      restart: always
      ports: 
        - 8080:8080
      volumes:
        - ./config/homer:/www/assets
        
    # Homeassistant
    homeassistant:
      image: homeassistant/home-assistant
      container_name: docker_homeassistant
      restart: always
      ports:
        -  8123:8123
      volumes:
        - ./config/homeassistant:/config
        - /run/dbus:/run/dbus:ro
      environment:
        - TZ=America/NewYork

    # Openhab
    openhab:
      image: openhab/openhab:4.1.3
      container_name: docker_openhab
      restart: always
      ports:
        - 8081:8080
        - 8444:8443
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - ./config/openhab:/openhab/conf
        - ./data/openhab/addons:/openhab/conf
        - ./data/openhab/userdata:/openhab/userdata
      environment:
        - CRYPTO_POLICY=unlimited"
        - EXTRA_JAVA_OPTS=-Duser.timezone=America/NewYork
        - OPENHAB_HTTP_PORT=8080
        - OPENHAB_HTTPS_PORT=8443

#    # Search for Torrents 
#    # QBittorrent
#    qbittorrent:
#      image: lscr.io/linuxserver/qbittorrent:latest
#      container_name: docker_qbittorrent
#      environment:
#        - VPN_USERNAME=
#        - VPN_PASSWORD=
#        - VPN_ENABLED=yes
#        - PUID=1000
#        - PGID=1000
#        - TZ=Etc/UTC
#        - WEBUI_PORT=8081
#        - INCOMING_PORT=8999
#        - TORRENTING_PORT=6881
#        - LAN_NETWORK=
#        - NAME_SERVERS=
#      volumes:
#        - ./config/qbittorrent:/config
#        - /mnt/plexStorage/Downloads:/downloads
#        - /mnt/TNas:/TNas
#        - /mnt/Anime:/Anime
#        - /etc/timezone/:/etc/timezone:ro
#      ports:
#        - 8081:8081
#        - 6881:6881
#        - 6881:6881/udp
#        - 8999:8999
#        - 8999:8999/udp
#      restart: always
#    # Jacket
#    Jackett:
#      image: "linuxserver/jackett"
#      container_name: "AniJackett"
#      volumes:
#        - ./config/jackett:/config
#        - /mnt/TNas/Downloading/:/downloads
#        - /mnt/Anime:/Anime
#        - /etc/timezone:/etc/timezone:ro #This is for TimeZone
#      ports:
#        - "9002:9117"    # WebUI
#      restart: always
#      environment:
#        - PUID=1000
#        - PGID=1000docker
#
#    Jackettv:
#      image: "linuxserver/jackett"
#      container_name: "Jackettv"
#      volumes:
#        - ./config/jackettv:/config
#        - /mnt/TNas/Downloading/:/downloads
#        - /mnt/Anime:/Anime
#        - /etc/timezone:/etc/timezone:ro #This is for TimeZone
#      ports:
#        - "9007:9117"    # WebUI
#      restart: always
#      environment:
#        - PUID=1000
#        - PGID=1000  
#    
#    # Sonarr
#    sonarr: # TV Shows
#      image: lscr.io/linuxserver/sonarr:latest
#      container_name: docker_sonarr
#      environment:
#        - PUID=1000
#        - PGID=1000
#        - TZ=Etc/UTC
#      volumes:
#        - ./config/sonarr:/config
#        - /mnt/plexStorage/TV:/tv #optional
#        - /mnt/plexStorage/Downloads:/downloads #optional
#      ports:
#        - 8989:8989
#      restart: always
#
#    radarr: # Movies
#      image: lscr.io/linuxserver/radarr:latest
#      container_name: docker_radarr
#      environment:
#        - PUID=1000
#        - PGID=1000
#        - TZ=Etc/UTC
#      volumes:
#        - ./config/radarr:/config
#        - /mnt/plexStorage/Movies:/movies #optional
#        - /mnt/plexStorage/Downloads:/downloads #optional
#      ports:
#        - 7878:7878
#      restart: always
#
#    lidarr: # Music
#      image: lscr.io/linuxserver/lidarr:latest
#      container_name: docker_lidarr
#      environment:
#        - PUID=1000
#        - PGID=1000
#        - TZ=Etc/UTC
#      volumes:
#        - ./config/lidarr:/config
#        - /mnt/plexStorage/music:/music #optional
#        - /mnt/plexStorage/downloads:/downloads #optional
#      ports:
#        - 8686:8686
#      restart: always
#
#    requestrr:
#      image: lscr.io/linuxserver/requestrr:latest
#      container_name: docker_requestrr
#      environment:
#        - PUID=1000
#        - PGID=1000
#        - TZ=Europe/London
#      volumes:
#        - ./config/requestrr:/config
#      ports:
#        - 4545:4545
#        - 8082:80
#      restart: always
#    
#    prowlarr: # Indexing Manager
#      image: lscr.io/linuxserver/prowlarr:latest
#      container_name: docker_prowlarr
#      environment:
#        - PUID=1000
#        - PGID=1000
#        - TZ=Etc/UTC
#      volumes:
#        - ./config/prowlarr:/config
#      ports:
#        - 9696:9696
#      restart: always


#
#      
#    plexserver:
#      container_name: docker_plex
#      restart: unless-stopped
#      build: 
#        context: .
#        dockerfile: Dockerfile.plex
#      environment:
#        - PUID=1000
#        - PGID=1000
#        - TZ=Etc/UTC
#        - VERSION=docker
#        - PLEX_CLAIM=claim-x5-zFxm4H1kuBykNn29c
#      volumes:
#        - ./config/plex:/config
#        - /mnt/plexStorage/:/mnt/plexStorage
##        - /mnt/plexStorage/TV\ Show/:/tv
#        - /mnt/plexStorage/Movies:/movies
#      ports:
#        - 32400:32400
#        - 1900:1900



